version: '3'

tasks:
  dev:
    cmds:
      - air -c .air.toml
  build:
    cmds:
      - goreleaser build --clean --snapshot
  release-local:
    cmds:
      - goreleaser release --clean --snapshot
  release:
    cmds:
      - goreleaser release --clean
