name: Publish release to Harbor

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish, e.g. v1.0.0"
        required: true
        type: string

  release:
    types: [published, created, edited]

env:
  HARBOR_URL: docker.ops.fntcloud.de

# permissions:
#   contents: write
#   packages: write

jobs:
  push-to-harbor:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "EVENT ${{ github.event_name }}"
          echo "RELEASE ${{ github.event.release }}"
          echo "TAG_NAME ${{ github.event.release.tag_name }}"
          echo "INPUTS.TAG ${{ inputs.tag }}"
      # - name: Login to Harbor Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: $HARBOR_URL
      #     username: ${{ secrets.HARBOR_USERNAME }}
      #     password: ${{ secrets.HARBOR_PASSWORD }}
            
