name: Publish release to Harbor

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish, e.g. v1.0.0"
        required: true
        type: string

  release:
    types: [published, created, edited]

jobs:
  push-to-harbor:
    runs-on: ubuntu-latest
    steps:
      - name: Process input
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "release: ${{ github.event.release }}"
          echo "release.tag_name: ${{ github.event.release.tag_name }}"
          echo "inputs.tag: ${{ inputs.tag }}"
          
          tag=${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.event.release.tag_name }}
          # remove trailing 'v'
          tag=$(echo $tag | sed 's/^v//')
          # make available to next steps
          echo "TAG: $tag"
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          
      # --tag ghcr.io/matthias-gruler-fnt/go-dummy:latest \
      - name: Push image to Harbor Registry
        run: |
          srcImg=ghcr.io/matthias-gruler-fnt/go-dummy:${{ env.TAG }}
          destImg=${{ env.HARBOR_REGISTRY }}/mgr/go-dummy:${{ env.TAG }}
          docker pull $srcImg
          docker tag $srcImg $destImg
          docker push $destImg
            
