name: Publish release to Harbor

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish, e.g. v1.0.0"
        required: true
        type: string

  release:
    types: [published, created, edited]

env:
  HARBOR_URL: docker.ops.fntcloud.de

# permissions:
#   contents: write
#   packages: write

jobs:
  push-to-harbor:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "EVENT ${{ github.event_name }}"
          echo "RELEASE ${{ github.event.release }}"
          echo "TAG_NAME ${{ github.event.release.tag_name }}"
          echo "INPUTS.TAG ${{ inputs.tag }}"
          echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          
      # --tag ghcr.io/matthias-gruler-fnt/go-dummy:latest \
      - name: Push image to Harbor Registry
        run: |
          srcImg=ghcr.io/matthias-gruler-fnt/go-dummy:${{ env.TAG }}
          destImg=$HARBOR_URL/mgr/go-dummy:${{ env.TAG }}
          docker pull $srcImg
          docker tag $srcImg $destImg
          docker push $destImg
            
